apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-sa
  namespace: argo
imagePullSecrets:
  - name: regcred
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: kaniko-build-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-build-rolebinding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: build-sa
    namespace: argo
roleRef:
  kind: Role
  name: kaniko-build-role
  apiGroup: rbac.authorization.k8s.io

